<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260928120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add provider-neutral organization analysis runs and review-only proposals';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
CREATE TABLE organization_runs (
    id UUID NOT NULL,
    requester_id UUID NOT NULL,
    producer_kind VARCHAR(32) NOT NULL,
    provider_name VARCHAR(160) DEFAULT NULL,
    model_name VARCHAR(255) DEFAULT NULL,
    model_version VARCHAR(255) DEFAULT NULL,
    status VARCHAR(32) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY(id),
    CONSTRAINT fk_organization_run_requester
        FOREIGN KEY (requester_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT chk_organization_run_producer
        CHECK (producer_kind IN ('metadata', 'ai_external', 'ai_local')),
    CONSTRAINT chk_organization_run_status
        CHECK (status IN ('draft', 'ready_for_review', 'failed', 'cancelled')),
    CONSTRAINT chk_organization_run_provider
        CHECK (
            (
                producer_kind = 'metadata'
                AND provider_name IS NULL
                AND model_name IS NULL
                AND model_version IS NULL
            )
            OR (
                producer_kind IN ('ai_external', 'ai_local')
                AND provider_name IS NOT NULL
                AND model_name IS NOT NULL
            )
        )
)
SQL);
        $this->addSql(
            'CREATE INDEX idx_organization_runs_requester
             ON organization_runs (requester_id, updated_at DESC)'
        );

        $this->addSql(<<<'SQL'
CREATE TABLE organization_run_media (
    run_id UUID NOT NULL,
    media_id UUID NOT NULL,
    position INT NOT NULL,
    PRIMARY KEY(run_id, media_id),
    CONSTRAINT fk_organization_run_media_run
        FOREIGN KEY (run_id) REFERENCES organization_runs (id) ON DELETE CASCADE,
    CONSTRAINT fk_organization_run_media_media
        FOREIGN KEY (media_id) REFERENCES media_assets (id) ON DELETE CASCADE,
    CONSTRAINT chk_organization_run_media_position CHECK (position >= 0)
)
SQL);
        $this->addSql(
            'CREATE INDEX idx_organization_run_media_media
             ON organization_run_media (media_id, run_id)'
        );

        $this->addSql(<<<'SQL'
CREATE TABLE organization_proposals (
    id UUID NOT NULL,
    run_id UUID NOT NULL,
    proposal_type VARCHAR(40) NOT NULL,
    status VARCHAR(32) NOT NULL,
    payload JSONB NOT NULL,
    rationale TEXT NOT NULL,
    reviewed_at TIMESTAMPTZ DEFAULT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY(id),
    CONSTRAINT fk_organization_proposal_run
        FOREIGN KEY (run_id) REFERENCES organization_runs (id) ON DELETE CASCADE,
    CONSTRAINT chk_organization_proposal_type
        CHECK (
            proposal_type IN (
                'smart_collection',
                'manual_collection',
                'tag',
                'review_bucket',
                'title_description',
                'cover'
            )
        ),
    CONSTRAINT chk_organization_proposal_status
        CHECK (status IN ('pending_review', 'rejected', 'applied', 'invalidated')),
    CONSTRAINT chk_organization_proposal_payload
        CHECK (jsonb_typeof(payload) = 'object'),
    CONSTRAINT chk_organization_proposal_rationale
        CHECK (btrim(rationale) <> '' AND char_length(rationale) <= 5000),
    CONSTRAINT uniq_organization_proposal_run UNIQUE (id, run_id)
)
SQL);
        $this->addSql(
            'CREATE INDEX idx_organization_proposals_run_status
             ON organization_proposals (run_id, status, created_at)'
        );

        $this->addSql(<<<'SQL'
CREATE TABLE organization_proposal_media (
    proposal_id UUID NOT NULL,
    run_id UUID NOT NULL,
    media_id UUID NOT NULL,
    position INT NOT NULL,
    PRIMARY KEY(proposal_id, media_id),
    CONSTRAINT fk_organization_proposal_media_proposal
        FOREIGN KEY (proposal_id, run_id)
        REFERENCES organization_proposals (id, run_id) ON DELETE CASCADE,
    CONSTRAINT fk_organization_proposal_media_scope
        FOREIGN KEY (run_id, media_id)
        REFERENCES organization_run_media (run_id, media_id) ON DELETE CASCADE,
    CONSTRAINT chk_organization_proposal_media_position CHECK (position >= 0)
)
SQL);
        $this->addSql(
            'CREATE INDEX idx_organization_proposal_media_media
             ON organization_proposal_media (media_id, proposal_id)'
        );

        $this->addSql(<<<'SQL'
CREATE TABLE organization_proposal_evidence (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    proposal_id UUID NOT NULL,
    source_kind VARCHAR(24) NOT NULL,
    summary TEXT NOT NULL,
    position INT NOT NULL,
    PRIMARY KEY(id),
    CONSTRAINT fk_organization_proposal_evidence_proposal
        FOREIGN KEY (proposal_id) REFERENCES organization_proposals (id) ON DELETE CASCADE,
    CONSTRAINT chk_organization_proposal_evidence_source
        CHECK (source_kind IN ('metadata', 'inference')),
    CONSTRAINT chk_organization_proposal_evidence_summary
        CHECK (btrim(summary) <> '' AND char_length(summary) <= 2000),
    CONSTRAINT chk_organization_proposal_evidence_position CHECK (position >= 0)
)
SQL);
        $this->addSql(
            'CREATE INDEX idx_organization_proposal_evidence_proposal
             ON organization_proposal_evidence (proposal_id, position)'
        );
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE organization_proposal_evidence');
        $this->addSql('DROP TABLE organization_proposal_media');
        $this->addSql('DROP TABLE organization_proposals');
        $this->addSql('DROP TABLE organization_run_media');
        $this->addSql('DROP TABLE organization_runs');
    }
}
